package devops.hw1.core;

public enum Phase {
	UNTAP1,
	UPKEEP1,
	DRAW1,
	FIRST_MAIN1,
	START_COMBAT1,
	DECLARE_ATTACKERS1,
	DECLARE_BLOCKERS1,
	COMBAT_DAMAGE1,
	END_OF_COMBAT1,
	SECOND_MAIN1,
	END1,
	CLEANUP1,
	UNTAP2,
	UPKEEP2,
	DRAW2,
	FIRST_MAIN2,
	START_COMBAT2,
	DECLARE_ATTACKERS2,
	DECLARE_BLOCKERS2,
	COMBAT_DAMAGE2,
	END_OF_COMBAT2,
	SECOND_MAIN2,
	END2,
	CLEANUP2;
}
