package devops.hw1.core;

public enum Phase {
	UNTAP1,
	UPKEEP1,
	DRAW1,
	FIRST_MAIN_PHASE1,
	START_COMBAT1,
	DECLARE_ATTACKERS1,
	DECLARE_BLOCKERS1,
	COMBAT_DAMAGE1,
	END_OF_COMBAT1, SECOND_MAIN_PHASE1, END_STEP1;
}
